export const FETCH_BOXES_REQUEST = "FETCH_BOXES_REQUEST";
export const FETCH_BOXES_SUCCESS = "FETCH_BOXES_SUCCESS";
export const FETCH_BOXES_FAILURE = "FETCH_BOXES_FAILURE"

export const INITIALIZE_FORM = "INITIALIZE_FORM";

export const REGISTER_BOX_REQUEST = "REGISTER_BOX_REQUEST";
export const REGISTER_BOX_SUCCESS = "REGISTER_BOX_SUCCESS";
export const REGISTER_BOX_FAILURE = "REGISTER_BOX_FAILURE";

export const UPDATE_BOX_FIELD = "UPDATE_BOX_FIELD";
